version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: as_postgres
    restart: always
    environment:
      POSTGRES_DB: awacs
      POSTGRES_PASSWORD: "awacs"
      POSTGRES_USER: awacs
    volumes:
      - "./awacs/postgresql/data:/var/lib/postgresql/data"
  redis:
    image: redis:4.0-alpine
    container_name: as_redis
    restart: always
  server:
    image: as_server:latest
    container_name: as_server
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - "./awacs/static:/dev/awacs/static"
      - "./awacs/logs:/dev/awacs/logs"
  nginx:
    image: as_nginx:latest
    container_name: as_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - redis
      - server
    volumes:
      - "./awacs/static:/web/nginx/static"
