# Generated by Django 3.1.3 on 2020-11-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('ts_code', models.CharField(max_length=16, verbose_name='TS代码')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='股票名称')),
                ('short_pinyin', models.CharField(db_index=True, max_length=16, verbose_name='拼音首字母')),
                ('area', models.CharField(max_length=128, verbose_name='所在地域')),
                ('industry', models.CharField(max_length=128, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=128, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=256, verbose_name='英文全称')),
                ('market', models.CharField(max_length=16, verbose_name='市场类型:主板/中小板/创业板/科创板')),
                ('exchange', models.CharField(max_length=16, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=16, verbose_name='交易货币')),
                ('list_status', models.CharField(max_length=16, verbose_name='上市状态:L上市 D退市 P暂停上市')),
                ('list_date', models.CharField(max_length=16, verbose_name='上市日期')),
                ('delist_date', models.CharField(max_length=16, null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(max_length=16, null=True, verbose_name='是否沪深港通标的:N否 H沪股通 S深股通')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeStock',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, null=True)),
                ('refer', models.FloatField(null=True)),
                ('remind_way', models.CharField(max_length=16, null=True)),
                ('template', models.CharField(max_length=16, null=True)),
                ('rose_percent', models.FloatField(null=True)),
                ('drop_percent', models.FloatField(null=True)),
                ('warn_price', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
