# Generated by Django 3.1.3 on 2020-11-12 03:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribestock',
            name='tech_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128, null=True), default=list, size=None),
        ),
    ]
