# Generated by Django 3.1.3 on 2020-11-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_subscribestock_tech_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('symbol', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Optional',
                'verbose_name_plural': 'Optional',
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.AlterModelOptions(
            name='subscribestock',
            options={'verbose_name': 'SubscribeStock', 'verbose_name_plural': 'SubscribeStock'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_hs',
            field=models.CharField(max_length=16, null=True, verbose_name='是否沪深港通标的'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='list_status',
            field=models.CharField(max_length=16, verbose_name='上市状态'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(max_length=16, verbose_name='市场类型'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='short_pinyin',
            field=models.CharField(db_index=True, max_length=16, verbose_name='简拼'),
        ),
    ]
