# Generated by Django 3.1.3 on 2020-11-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201123_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdQueryRose',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16, verbose_name='股票代码')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='股票名称')),
                ('short_pinyin', models.CharField(db_index=True, max_length=16, verbose_name='简拼')),
                ('owner', models.CharField(db_index=True, max_length=16, verbose_name='Owner')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'CmdQueryRose',
                'verbose_name_plural': 'CmdQueryRose',
            },
        ),
    ]
