# Generated by Django 3.1.3 on 2020-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_cmdqueryrose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdqueryrose',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
